import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="fixed w-full h-12 top-0 text-center text-zinc bg-air">
          <Navbar/>
        </div>
 
        
        {children}
        <div className="">
          <Footer />
        </div>
        </body>
    </html>
  )
}
{/** 
<div className="fixed w-full h-24 top-0 p-3 text-center text-zinc bg-air">
          <Navbar/>
        </div>
 */}
